In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Loading the dataset

In [ ]:
dataset = pd.read_csv(r'/content/drive/My Drive/Colab Notebooks/train.csv')

# Loading data to variable

In [ ]:
dataset.shape

dataset = dataset.dropna() #dropping rows with no data
dataset.shape
dataset
y = dataset.iloc[:, -1].values
X = dataset.iloc[:,[1,3]] # storing column 1 and 3 into X
print(len(dataset))
print(dataset['title'].shape)
print(dataset['text'].shape)
#X.reset_index(inplace=True)
y = np.reshape(y,(18285, 1))
y.shape

18285
(18285,)
(18285,)


(18285, 1)

# Cleaning the text

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
title1 = []
text1 = []
for i,v in enumerate(X['title']):
    titl = re.sub('[^a-zA-Z]', ' ', v) #Taking only text 'a-z & A-Z' and replacing other things with a space
    titl = titl.lower() #converting the text into lowercase
    titl = titl.split() #splitting to get a list of words
    ps = PorterStemmer() #instanciating PorterStemmer for Stemming
    titl = [ps.stem(word) for word in titl if not word in set(stopwords.words('english'))] # removing useless words in english eg: i, me, is, am while containing the meaning
    titl = ' '.join(titl) # Joining the semmed words into a single line
    title1.append(titl)

#for i,v in enumerate(X['text']):
#    text = re.sub('[^a-zA-Z]', ' ', v)
#    text = text.lower()
#    text = text.split()
#    ps = PorterStemmer()
#    text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
#    text = ' '.join(text)
#    text1.append(text)

#text

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
len(text1)
len(title1)


NameError: ignored

In [ ]:
a = [[1,2,3],[4,5,6]]
len(a)

2

# Creating Bag of Word Model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() #Instanciating CountVectorizer
x = cv.fit_transform(title1).toarray() # taking each word converting their occurance into an array
y = dataset.iloc[:, -1].values # loading the labels
print(x.shape)


(18285, 13913)


# Splitting dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0) #splitting the dataset into 80% data for training and 20% for testing

# Training SVM model

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# Training KNN model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

# Predicting for KNN and forming confusion matrix

In [ ]:
y_pred=neigh.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1282  758]
 [   5 1612]]


# Predicting for SVM and forming confusion matrix

In [ ]:
y_pred=clf.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1792  248]
 [  26 1591]]


# Training model for Random FOrest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state=0)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

# Predicting for Random Forest and forming confusion matrix

In [ ]:
y_pred=clf.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1845  195]
 [  76 1541]]


In [ ]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences

from keras.preprocessing.text import one_hot

In [ ]:
voc_size=5000
onehot_repr=[one_hot(words,voc_size)for words in title1] 
onehot_repr

[[850, 3618, 1813, 3327, 2070, 1423, 2234, 2478, 4692, 1678],
 [868, 1603, 3781, 2332, 2020, 433, 4170],
 [719, 1827, 2849, 943],
 [1053, 2269, 893, 4989, 2851, 4707],
 [2509, 2020, 1798, 4526, 2336, 4310, 2020, 2833, 3218, 389],
 [2486,
  3750,
  2042,
  1589,
  182,
  1498,
  3220,
  4085,
  3884,
  2995,
  323,
  3824,
  1302,
  724,
  4170],
 [1965, 2089, 4865, 4271, 512, 1195, 2062, 1156, 103, 1653, 831],
 [2097, 3988, 3677, 2099, 698, 1916, 1498, 1305, 103, 1653, 831],
 [4785, 1487, 3948, 2733, 1469, 4903, 1983, 4725, 1498, 3778],
 [2282, 1450, 1364, 2939, 4676, 577, 2246, 430],
 [1892, 1996, 3122, 1384, 1703, 2029, 939, 2082, 462, 4691, 3297],
 [4989, 3522, 2070, 4903, 1498, 698],
 [2490, 1058, 247, 4286, 3751, 2373, 3189, 661, 183],
 [4838, 1401, 2149, 3706, 2957, 2571, 3827, 103, 1653, 831],
 [1159, 898, 2721, 2291, 2365, 103, 1653, 831],
 [3984, 4623, 4305, 4392, 1038, 3656, 2144, 4772, 1749, 3705],
 [1237, 1728, 1603],
 [3245, 3447, 4464, 627, 1498, 2230, 286, 4170],
 [4405,

In [ ]:


sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)



[[   0    0    0 ... 2478 4692 1678]
 [   0    0    0 ... 2020  433 4170]
 [   0    0    0 ... 1827 2849  943]
 ...
 [   0    0    0 ...  103 1653  831]
 [   0    0    0 ... 3143 4796 1248]
 [   0    0    0 ... 4991 2107  432]]


In [ ]:
import numpy as np
y = dataset.iloc[:, -1].values
x=np.array(embedded_docs)
y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0) #splitting the dataset into 80% data for training and 20% for testing

In [ ]:
import array as a
y = a.array('i',y)

y.shape[1]

IndexError: ignored

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import LSTM

In [ ]:
embedding_vector_features=40
classifier = Sequential()
#classifier.add(Dense(units = 20, kernel_initializer = 'he_uniform', activation='relu',input_dim=13913))
classifier.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

#classifier.add(Dropout(0.3))
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform', activation='relu'))
classifier.add(Dense(units = 10, kernel_initializer = 'he_uniform', activation='relu'))
#classifier.add(Dense(units = 10, kernel_initializer = 'he_uniform', activation='relu'))
#classifier.add(Dense(units = 150, kernel_initializer = 'he_uniform', activation='relu'))
#classifier.add(Dense(units = 250, kernel_initializer = 'he_uniform', activation='relu'))
#classifier.add(Dense(output_dim=1, init='glorot_uniform', activation='sigmoid'))
classifier.add(Flatten())
classifier.add(Dense(1, activation='sigmoid'))
classifier.compile(optimizer='Adamax', loss='binary_crossentropy',metrics=['accuracy'])



In [ ]:
model_history = classifier.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=64,nb_epoch=10)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 14628 samples, validate on 3657 samples
Epoch 1/10
14628/14628 [==============================] - 1s 94us/step - loss: 0.4998 - accuracy: 0.7319 - val_loss: 0.3102 - val_accuracy: 0.8791
Epoch 2/10
14628/14628 [==============================] - 1s 75us/step - loss: 0.2342 - accuracy: 0.9070 - val_loss: 0.2142 - val_accuracy: 0.9089
Epoch 3/10
14628/14628 [==============================] - 1s 75us/step - loss: 0.1691 - accuracy: 0.9301 - val_loss: 0.1918 - val_accuracy: 0.9163
Epoch 4/10
14628/14628 [==============================] - 1s 76us/step - loss: 0.1405 - accuracy: 0.9451 - val_loss: 0.1854 - val_accuracy: 0.9218
Epoch 5/10
14628/14628 [==============================] - 1s 78us/step - loss: 0.1194 - accuracy: 0.9547 - val_loss: 0.1835 - val_accuracy: 0.9262
Epoch 6/10
14628/14628 [==============================] - 1s 79us/step - loss: 0.1017 - accuracy: 0.9637 - val_loss: 0.1856 - val_accuracy: 0.9256
Epoch 7/10
14628/14628 [==============================] - 1s 74us/ste

In [ ]:


embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])



In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
229/229 [==============================] - 7s 31ms/step - loss: 0.3198 - accuracy: 0.8475 - val_loss: 0.1836 - val_accuracy: 0.9207
Epoch 2/10
229/229 [==============================] - 7s 29ms/step - loss: 0.1543 - accuracy: 0.9389 - val_loss: 0.1765 - val_accuracy: 0.9221
Epoch 3/10
229/229 [==============================] - 7s 29ms/step - loss: 0.1229 - accuracy: 0.9517 - val_loss: 0.1883 - val_accuracy: 0.9223
Epoch 4/10
229/229 [==============================] - 7s 28ms/step - loss: 0.1001 - accuracy: 0.9621 - val_loss: 0.1967 - val_accuracy: 0.9188
Epoch 5/10
229/229 [==============================] - 7s 28ms/step - loss: 0.0818 - accuracy: 0.9717 - val_loss: 0.2354 - val_accuracy: 0.9199
Epoch 6/10
229/229 [==============================] - 7s 29ms/step - loss: 0.0641 - accuracy: 0.9768 - val_loss: 0.2725 - val_accuracy: 0.9199
Epoch 7/10
229/229 [==============================] - 7s 28ms/step - loss: 0.0495 - accuracy: 0.9828 - val_loss: 0.2644 - val_accuracy: 0.9188

In [ ]:
y_pred=model.predict(X_test)
y_pred=(y_pred>0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1875  165]
 [ 148 1469]]


In [ ]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1851  189]
 [  96 1521]]


In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred,y_test)
score

0.9144107191687175

In [ ]:
score = accuracy_score(y_pred,y_test)
score

0.9220672682526662